### ISSUE TITLE
cc3d python API documentation unavailable (within Twedit)

### ISSUE THREAD

**Issue by sminsuk** [CompuCell3D/cc3d-twedit5#54]
**Describe the bug**
No documentation is available for the cc3d python API

**To Reproduce**
1. In Twedit, go to, and select, menu item: CC3D Python > Show Code Developer Reference Panel
2. Error message appears: Error opening ...CompuCell3D/miniconda3/lib/python3.10/site-packages/cc3d/doc/code_ref/developer/html/ No such file or directory. QtNetwork Error 203
3. Navigate to the indicated directory
4. Observe that directory is present, but is indeed empty.
5. Try the same with Show Code User Reference Panel: same result (slightly different directory is also present, but empty)
 
**Expected behavior**
Documentation should appear.

**Desktop(please complete the following information):**
 - Device: MacBook Pro
 - Processor M1
 - OS: macOS Monterey (12.7.2)
 - CompuCell3D Version and commit tag : Version 4.6.0 rev. 2 Commit tag: 397f8b1
 - How did you install the code : binary installer
 - File name of the installer used to install CC3D: cc3d-installer-osx-4.6.0-arm64.sh
 

**Additional context**
Without this documentation, I'm unable to replicate and register in python, the AdhesionFlex specs that I have running in my XML-based version. I managed to guess correctly all my other modules! But AdhesionFlex has a very complex spec structure, and when I try it, my simulation segfaults during sim.run(). In addition, I have a couple other issues where my sim does not behave correctly or the same, from pure python, run in PyCharm, as it does from XML version run in Twedit. Right now I need either some 1-on-1 help, or documentation. I'm blocked otherwise.

**Comment by sminsuk** [comment]
Additional information. I realized that I have **_both_** installations, one from the binary installer, and one from a conda install, which I set up separately in order to do python-based coding in my IDE. I was not sure if Twedit even existed in there, but I tried to find it. I conda-activated the relevant environment and typed "twedit" and a separate Twedit instance launched. (I had an instance from the binary installer already open.) I tried to get the documentation from this second instance of Twedit. Still, no luck. Same result. I also got the following message in my Terminal window:

```
Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/Users/sminsuk/miniconda3/envs/cc3d4_6_py3_10/lib/python3.10/site-packages/sphinx/config.py", line 529, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/Users/sminsuk/miniconda3/envs/cc3d4_6_py3_10/lib/python3.10/site-packages/cc3d/doc/code_ref/developer/build/conf.py", line 34, in <module>
    graphviz_dot = [x for x in os.listdir(os.path.join(os.path.dirname(sys.executable), *graphviz_reldirs))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sminsuk/miniconda3/envs/cc3d4_6_py3_10/bin/bin'
```
